version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: ./docker/app/Dockerfile
    command: "bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: "development"
      RAILS_LOG_TO_STDOUT: "ENABLE"
      LAUNCHY_DRY_RUN: "true"
      BROWSER: "/dev/null"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    build:
      context: ../..
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:8080

volumes:
  db_data:
