AllCops:
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: False

Layout/SpaceAroundMethodCallOperator:
  Enabled: False

Lint/AssignmentInCondition:
  Enabled: False

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: True

Lint/DeprecatedOpenSSLConstant:
  Enabled: True

Lint/DuplicateElsifCondition:
  Enabled: True

Lint/DuplicateRescueException:
  Enabled: True

Lint/EmptyConditionalBody:
  Enabled: True

Lint/FloatComparison:
  Enabled: True

Lint/MissingSuper:
  Enabled: True

Lint/MixedRegexpCaptureTypes:
  Enabled: True

Lint/OutOfRangeRegexpRef:
  Enabled: True

Lint/RaiseException:
  Enabled: True

Lint/SelfAssignment:
  Enabled: True

Lint/StructNewOverride:
  Enabled: True

Lint/TopLevelReturnWithArgument:
  Enabled: True

Lint/UnreachableLoop:
  Enabled: True

Lint/UriEscapeUnescape:
  Enabled: True

Metrics/BlockLength:
  Exclude:
    - "config/**/*.rb"

Naming/AccessorMethodName:
  Enabled: True

Naming/MethodName:
  Enabled: True

Naming/PredicateName:
  Enabled: True

Style/AccessorGrouping:
  Enabled: True

Style/ArrayCoercion:
  Enabled: True

Style/BisectedAttrAccessor:
  Enabled: True

Style/CaseLikeIf:
  Enabled: True

Style/Documentation:
  Exclude:
    - "db/migrate/*.rb"
    - "test/**/*.rb"

Style/DoubleNegation:
  Enabled: False

Style/EmptyMethod:
  EnforcedStyle: "expanded"

Style/ExplicitBlockArgument:
  Enabled: True

Style/ExponentialNotation:
  Enabled: False

Style/GlobalStdStream:
  Enabled: True

Style/HashAsLastArrayItem:
  Enabled: True

Style/HashEachMethods:
  Enabled: True

Style/HashLikeCase:
  Enabled: True

Style/HashTransformKeys:
  Enabled: True

Style/HashTransformValues:
  Enabled: True

Style/MissingRespondToMissing:
  Enabled: True

Style/OptionalBooleanParameter:
  Enabled: True

# i think #has_key? and #has_value? are much clearer than #key? and #value?
Style/PreferredHashMethods:
  EnforcedStyle: "verbose"

Style/RedundantAssignment:
  Enabled: True

Style/RedundantFetchBlock:
  Enabled: True

Style/RedundantFileExtensionInRequire:
  Enabled: True

Style/RedundantRegexpCharacterClass:
  Enabled: True

Style/RedundantRegexpEscape:
  Enabled: True

# prefer rescue => e over rescue StandardError => e
Style/RescueStandardError:
  EnforcedStyle: "implicit"

Style/SingleArgumentDig:
  Enabled: True

Style/SlicingWithRange:
  Enabled: True

# i think sometimes concatenation is more legible
Style/StringConcatenation:
  Enabled: False
