version: '3.1'
services:
  app:
    image: 879062616596.dkr.ecr.us-east-2.amazonaws.com/cybersecurity-messenger:production
    build:
      context: ../..
      dockerfile: ./docker/app/Dockerfile
    command: "bundle exec puma -C config/puma.rb"
  nginx:
    image: 879062616596.dkr.ecr.us-east-2.amazonaws.com/messenger-nginx:production
    build:
      context: ../..
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
