# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.db_host[Rails.env.to_sym] %>
  username: <%= Rails.application.credentials.db_username[Rails.env.to_sym] %>
  password: <%= Rails.application.credentials.db_password[Rails.env.to_sym] %>

development:
  <<: *default
  host: localhost
  username: postgres
  database: messenger_development
  password:

test:
  <<: *default
  host: localhost
  username: postgres
  database: messenger_test
  password:

production:
  <<: *default
  database: messenger_production
